name: pt2.0.1
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - aiofiles=22.1.0=py311haa95532_0
  - aiosqlite=0.18.0=py311haa95532_0
  - anyio=3.5.0=py311haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py311haa95532_0
  - babel=2.11.0=py311haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py311h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - certifi=2023.7.22=py311haa95532_0
  - cffi=1.15.1=py311h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py311haa95532_0
  - comm=0.1.2=py311haa95532_0
  - cryptography=41.0.2=py311hac1b9e3_0
  - cuda-cccl=12.2.140=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - debugpy=1.6.7=py311hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.9.0=py311haa95532_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - idna=3.4=py311haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.0=py311h746a85d_0
  - ipython=8.12.2=py311haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py311haa95532_1
  - jinja2=3.1.2=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311haa95532_0
  - jupyter_client=7.4.9=py311haa95532_0
  - jupyter_core=5.3.0=py311haa95532_0
  - jupyter_events=0.6.3=py311haa95532_0
  - jupyter_server=1.23.4=py311haa95532_0
  - jupyter_server_fileid=0.9.0=py311haa95532_0
  - jupyter_server_ydoc=0.8.0=py311haa95532_1
  - jupyter_ydoc=0.2.4=py311haa95532_0
  - jupyterlab=3.6.3=py311haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311haa95532_0
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.3.141=0
  - libcurand-dev=10.3.3.141=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lxml=4.9.2=py311h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py311h2bbff1b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - mistune=0.8.4=py311h2bbff1b_1000
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.6=py311hf62ec03_1
  - mkl_random=1.2.2=py311hf62ec03_1
  - mpmath=1.3.0=py311haa95532_0
  - nbclassic=0.5.5=py311haa95532_0
  - nbclient=0.5.13=py311haa95532_0
  - nbconvert=6.5.4=py311haa95532_0
  - nbformat=5.7.0=py311haa95532_0
  - nest-asyncio=1.5.6=py311haa95532_0
  - networkx=3.1=py311haa95532_0
  - notebook=6.5.4=py311haa95532_1
  - notebook-shim=0.2.2=py311haa95532_0
  - openssl=3.0.10=h2bbff1b_2
  - packaging=23.1=py311haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311hd77b12b_0
  - pip=23.2.1=py311haa95532_0
  - platformdirs=3.10.0=py311haa95532_0
  - prometheus_client=0.14.1=py311haa95532_0
  - prompt-toolkit=3.0.36=py311haa95532_0
  - psutil=5.9.0=py311h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311haa95532_1
  - pyopenssl=23.2.0=py311haa95532_0
  - pyrsistent=0.18.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.9
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311haa95532_0
  - python-json-logger=2.0.7=py311haa95532_0
  - pytorch=2.0.1=py3.11_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py311haa95532_0
  - pywin32=305=py311h2bbff1b_0
  - pywinpty=2.0.10=py311h5da7b33_0
  - pyzmq=23.2.0=py311hd77b12b_0
  - requests=2.31.0=py311haa95532_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - rfc3986-validator=0.1.1=py311haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=68.0.0=py311haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py311haa95532_1
  - soupsieve=2.4=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py311haa95532_0
  - tinycss2=1.2.1=py311haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.3.2=py311h2bbff1b_0
  - traitlets=5.7.1=py311haa95532_0
  - urllib3=1.26.16=py311haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311haa95532_1
  - websocket-client=0.58.0=py311haa95532_4
  - wheel=0.38.4=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py311hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - ypy-websocket=0.8.2=py311haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==1.4.0
      - addict==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - aistudio-sdk==0.3.8
      - albucore==0.0.24
      - albumentations==2.0.7
      - altgraph==0.17.4
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - astor==0.8.1
      - basicsr==1.4.2
      - bce-python-sdk==0.9.46
      - blinker==1.6.3
      - blosc2==2.7.0
      - cachetools==5.3.1
      - captum==0.6.0
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorlog==6.10.1
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.19.0
      - descartes==1.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - facexlib==0.3.0
      - filterpy==1.4.5
      - fipy==4.0.1
      - flask==3.0.0
      - fonttools==4.42.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - gfpgan==1.3.8
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.58.0
      - h11==0.16.0
      - h5py==3.10.0
      - hdf5storage==0.1.19
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.22.2
      - imageio==2.35.1
      - imagesize==1.4.1
      - itsdangerous==2.1.2
      - joblib==1.3.2
      - json-tricks==3.17.3
      - jsonlines==4.0.0
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - lightning-utilities==0.9.0
      - llvmlite==0.43.0
      - lmdb==1.7.5
      - lpips==0.1.4
      - markdown==3.4.4
      - markdown-it-py==4.0.0
      - mat4py==0.6.0
      - matplotlib==3.7.2
      - mdurl==0.1.2
      - modelscope==1.31.0
      - mouseinfo==0.1.3
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - ndindex==1.8
      - nni==3.0
      - numba==0.60.0
      - numexpr==2.10.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-ml-py==12.560.30
      - nvidia-nvjitlink-cu12==12.9.86
      - oauthlib==3.2.2
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - pandas==2.1.1
      - pefile==2023.2.7
      - polars==1.35.0
      - polars-runtime-32==1.35.0
      - prettytable==3.11.0
      - protobuf==3.20.2
      - py-cpuinfo==9.0.0
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyautogui==0.9.54
      - pyclipper==1.3.0.post6
      - pycryptodome==3.23.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygetwindow==0.0.9
      - pyinstaller==6.0.0
      - pyinstaller-hooks-contrib==2023.9
      - pymsgbox==1.0.9
      - pyod==2.0.1
      - pyparsing==3.0.9
      - pypdfium2==5.0.0
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - python-bidi==0.6.7
      - python-docx==1.2.0
      - python-graphviz==0.20.3
      - pythonwebhdfs==0.2.3
      - pytweening==1.2.0
      - pywin32-ctypes==0.2.2
      - pyyaml==6.0.2
      - qtpy==2.4.0
      - regex==2024.4.28
      - requests-oauthlib==1.3.1
      - responses==0.25.3
      - rich==14.2.0
      - rsa==4.9
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - safetensors==0.6.2
      - schema==0.7.7
      - scikit-image==0.24.0
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.13.2
      - sentry-sdk==1.40.3
      - setproctitle==1.3.3
      - shapely==2.1.1
      - shellingham==1.5.4
      - simplejson==3.19.3
      - simsimd==6.2.1
      - smmap==5.0.1
      - stringzilla==3.12.5
      - tables==3.9.2
      - tb-nightly==2.21.0a20251023
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.2.0
      - tifffile==2024.8.30
      - timm==1.0.22
      - tokenizers==0.19.1
      - torchaudio==2.0.2
      - torchmetrics==1.1.1
      - torchvision==0.15.2
      - tqdm==4.66.1
      - transformers==4.40.1
      - typeguard==4.1.2
      - typer==0.20.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2023.3
      - ujson==5.11.0
      - ultralytics==8.3.221
      - ultralytics-thop==2.0.17
      - wandb==0.16.3
      - websockets==12.0
      - werkzeug==3.0.0
      - widgetsnbextension==4.0.9
      - xxhash==3.4.1
      - yapf==0.43.0
      - yarl==1.9.4
prefix: D:\ANAconda\envs\pt2.0.1
